# Generated by Django 5.2 on 2025-05-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='room',
        ),
        migrations.RemoveField(
            model_name='table',
            name='type',
        ),
        migrations.RemoveField(
            model_name='groupstudent',
            name='table',
        ),
        migrations.DeleteModel(
            name='TableType',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
