from .otp_view import *
from .group_view import *
from .teacher_view import *
from .payment_view import *
from .attendance_view import *
from .student_view import *
from .statistics_view import *
from .register_view import *
from .login import *
from .user_view import *
from .homework_view import *